# SBBD - Tratamento de dados

## Importação e leitura de dados

In [1]:
!pip3 install pysus==1.0.1

Collecting pysus==1.0.1
  Downloading pysus-1.0.1-py3-none-any.whl.metadata (1.3 kB)
Collecting Unidecode<2.0.0,>=1.3.6 (from pysus==1.0.1)
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Collecting aioftp<0.22.0,>=0.21.4 (from pysus==1.0.1)
  Downloading aioftp-0.21.4-py3-none-any.whl.metadata (6.1 kB)
Collecting bigtree<0.13.0,>=0.12.2 (from pysus==1.0.1)
  Downloading bigtree-0.12.5-py3-none-any.whl.metadata (28 kB)
Collecting dateparser<2.0.0,>=1.1.8 (from pysus==1.0.1)
  Downloading dateparser-1.4.1-py3-none-any.whl.metadata (22 kB)
Collecting dbfread==2.0.7 (from pysus==1.0.1)
  Downloading dbfread-2.0.7-py2.py3-none-any.whl.metadata (3.3 kB)
Collecting elasticsearch==7.16.2 (from elasticsearch[preprocessing]==7.16.2->pysus==1.0.1)
  Downloading elasticsearch-7.16.2-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting fastparquet<=2024.11.0,>=2023.10.1 (from pysus==1.0.1)
  Downloading fastparquet-2024.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from pysus==1.0.1) (4.15.0)
Collecting loguru<0.7.0,>=0.6.0 (from pysus==1.0.1)
  Downloading loguru-0.6.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: numpy<3,>1 in /usr/local/lib/python3.12/dist-packages (from pysus==1.0.1) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from pysus==1.0.1) (2.2.2)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.12/dist-packages (from pysus==1.0.1) (18.1.0)
Collecting pycparser==2.21 (from pysus==1.0.1)
  Downloading pycparser-2.21-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting pyreaddbc>=1.1.0 (from pysus==1.0.1)
  Downloading pyreaddbc-2.0.4-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting python-dateutil==2.8.2 (from pysus==1.0.1)
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl.metadata (8.2 kB)
Collecting tqdm==4.64.0 (from pysus==1.0.1)
  Downloading tqdm-4.64.0-py2.py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from pysus==1.0.1) (4.15.0)
Collecting urwid<3.0.0,>=2.1.2 (from pysus==1.0.1)
  Downloading urwid-2.6.16-py3-none-any.whl.metadata (11 kB)
Collecting wget<4.0,>=3.2 (from pysus==1.0.1)
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Collecting urllib3<2,>=1.21.1 (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus==1.0.1)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from elasticsearch==7.16.2->elasticsearch[preprocessing]==7.16.2->pysus==1.0.1) (2026.5.20)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil==2.8.2->pysus==1.0.1) (1.17.0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus==1.0.1) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus==1.0.1) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus==1.0.1) (5.3.1)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus==1.0.1) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus==1.0.1) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from fastparquet<=2024.11.0,>=2023.10.1->pysus==1.0.1) (26.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.2.2->pysus==1.0.1) (2026.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from urwid<3.0.0,>=2.1.2->pysus==1.0.1) (0.8.1)
Downloading pysus-1.0.1-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 21.8 MB/s eta 0:00:00
Downloading dbfread-2.0.7-py2.py3-none-any.whl (20 kB)
Downloading elasticsearch-7.16.2-py2.py3-none-any.whl (385 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 26.8 MB/s eta 0:00:00
Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 8.1 MB/s eta 0:00:00
Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 15.1 MB/s eta 0:00:00
Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 5.8 MB/s eta 0:00:00
Downloading aioftp-0.21.4-py3-none-any.whl (37 kB)
Downloading bigtree-0.12.5-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 5.0 MB/s eta 0:00:00
Downloading dateparser-1.4.1-py3-none-any.whl (300 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.5/300.5 kB 17.8 MB/s eta 0:00:00
Downloading fastparquet-2024.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 19.7 MB/s eta 0:00:00
Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 4.6 MB/s eta 0:00:00
Downloading pyreaddbc-2.0.4-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 kB 3.7 MB/s eta 0:00:00
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 18.8 MB/s eta 0:00:00
Downloading urwid-2.6.16-py3-none-any.whl (297 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.2/297.2 kB 20.5 MB/s eta 0:00:00
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 9.0 MB/s eta 0:00:00
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=d3e00153d31cbbb867cc0e296b68948cfc20d8e5f102d0b31d6fe00fd3df7f90
  Stored in directory: /root/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget
Installing collected packages: wget, dbfread, urwid, urllib3, Unidecode, tqdm, python-dateutil, pyreaddbc, pycparser, loguru, bigtree, aioftp, elasticsearch, dateparser, fastparquet, pysus
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.3
    Uninstalling tqdm-4.67.3:
      Successfully uninstalled tqdm-4.67.3
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: pycparser
    Found existing installation: pycparser 3.0
    Uninstalling pycparser-3.0:
      Successfully uninstalled pycparser-3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
holidays 0.98 requires python-dateutil<3,>=2.9.0.post0, but you have python-dateutil 2.8.2 which is incompatible.
google-adk 1.29.0 requires python-dateutil<3.0.0,>=2.9.0.post0, but you have python-dateutil 2.8.2 which is incompatible.
datasets 4.0.0 requires tqdm>=4.66.3, but you have tqdm 4.64.0 which is incompatible.
spopt 0.7.0 requires tqdm>=4.66.0, but you have tqdm 4.64.0 which is incompatible.
momepy 0.11.0 requires tqdm>=4.65, but you have tqdm 4.64.0 which is incompatible.
dopamine-rl 4.1.2 requires tqdm>=4.64.1, but you have tqdm 4.64.0 which is incompatible.
tobler 0.14.0 requires tqdm>=4.67, but you have tqdm 4.64.0 which is incompatible.
dataproc-spark-connect 1.1.0 requires tqdm>=4.67, but you have tqdm 4.64.0 which is incompatible.
blobfile 3.2.0 requires urllib3>=2, but you have urllib3 1.26.20 which is incompatible.
Successfully installed Unidecode-1.4.0 aioftp-0.21.4 bigtree-0.12.5 dateparser-1.4.1 dbfread-2.0.7 elasticsearch-7.16.2 fastparquet-2024.11.0 loguru-0.6.0 pycparser-2.21 pyreaddbc-2.0.4 pysus-1.0.1 python-dateutil-2.8.2 tqdm-4.64.0 urllib3-1.26.20 urwid-2.6.16 wget-3.2

In [3]:
from pysus.ftp.databases.sinan import SINAN

In [4]:
import gdown
import geopandas as gpd
import numpy as np
import pandas as pd

### Importação e leitura

In [5]:
sinan = SINAN().load()

In [ ]:
# sinan.metadata

In [ ]:
# sinan.diseases

In [6]:
# Pega todos os arquivos disponíveis para acidentes por animais peçonhentos
files = sinan.get_files(dis_code="ANIM")

dfs = []

for file in files:
    print(f"Baixando {file}...")

    parquet = file.download()
    df_temp = parquet.to_dataframe()

    dfs.append(df_temp)

# Junta todos os anos em um único DataFrame
df_anim = pd.concat(dfs, ignore_index=True)

df_anim.head()

Baixando ANIMBR07.dbc...
Baixando ANIMBR08.dbc...
Baixando ANIMBR09.dbc...
Baixando ANIMBR10.dbc...
Baixando ANIMBR11.dbc...
Baixando ANIMBR12.dbc...
Baixando ANIMBR13.dbc...
Baixando ANIMBR14.dbc...
Baixando ANIMBR15.dbc...
Baixando ANIMBR16.dbc...
Baixando ANIMBR17.dbc...
Baixando ANIMBR18.dbc...
Baixando ANIMBR19.dbc...
Baixando ANIMBR20.dbc...
Baixando ANIMBR21.dbc...
Baixando ANIMBR22.dbc...
Baixando ANIMBR23.dbc...
Baixando ANIMBR24.dbc...
Baixando ANIMBR25.dbc...
Baixando ANIMBR26.dbc...

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,DT_SIN_PRI,SEM_PRI,...,COM_SISTEM,COM_RENAL,COM_EDEMA,COM_SEPTIC,COM_CHOQUE,DOENCA_TRA,EVOLUCAO,DT_OBITO,DT_ENCERRA,DT_DIGITA
0,2,X29,2007-03-05,200710,2007,15,150800,1485,2007-03-05,200710,...,2,,,,,,1,00000000,20070516,20070516
1,2,X29,2007-03-31,200713,2007,35,353390,1339,2007-03-31,200713,...,2,,,,,2,1,00000000,20070331,20070409
2,2,X29,2007-03-31,200713,2007,35,353390,1339,2007-03-31,200713,...,2,,,,,2,1,00000000,20070331,20070409
3,2,X29,2007-03-23,200712,2007,35,353390,1339,2007-03-23,200712,...,2,,,,,2,1,00000000,20070323,20070327
4,2,X29,2007-03-01,200709,2007,35,353390,1339,2007-03-01,200709,...,2,,,,,2,1,00000000,20070301,20070312

In [17]:
df_anim.columns

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'SG_UF_NOT',
       'ID_MUNICIP', 'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF',
       'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N',
       'ANT_DT_ACI', 'ANT_UF', 'ANT_MUNIC_', 'ANT_TEMPO_', 'ANT_LOCA_1',
       'MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO', 'CLI_NECROS',
       'CLI_LOCAL_', 'CLI_LOCA_1', 'MCLI_SIST', 'CLI_NEURO', 'CLI_HEMORR',
       'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2', 'CLI_OUTR_3',
       'CLI_TEMPO_', 'TP_ACIDENT', 'ANI_TIPO_1', 'ANI_SERPEN', 'ANI_ARANHA',
       'ANI_LAGART', 'TRA_CLASSI', 'CON_SOROTE', 'NU_AMPOLAS', 'NU_AMPOL_1',
       'NU_AMPOL_8', 'NU_AMPOL_6', 'NU_AMPOL_4', 'NU_AMPO_7', 'NU_AMPO_5',
       'NU_AMPOL_9', 'NU_AMPOL_3', 'COM_LOC', 'COM_SECUND', 'COM_NECROS',
       'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM', 'COM_RENAL',
       'COM_EDEMA', 'COM_SEPTIC', 'COM_CHOQUE', 'DOENCA_TRA', 'EVOLUCAO',
       'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA'],
      dtype='object')

In [ ]:
# df_anim.dtypes

In [7]:
df_anim.shape

(4280892, 75)

In [ ]:
# df_anim.to_csv("df_anim.csv", index=False) #apenas para não perder os dados em caso de desconexão

In [11]:
# Divisões de Saúde do estado de São Paulo
!gdown 1U94NZDIqgTXQPaBtmv7ZYxJNowN7XxQW --output divisoes.gpkg

Downloading...
From: https://drive.google.com/uc?id=1U94NZDIqgTXQPaBtmv7ZYxJNowN7XxQW
To: /content/divisoes.gpkg
100% 15.0M/15.0M [00:00<00:00, 26.1MB/s]

In [12]:
# ---- Divisões de Saúde ---- #
gdf_munic = gpd.read_file('divisoes.gpkg')

# Segunda geometria para os municipios
gdf_munic['coordenadas'] = gpd.points_from_xy(gdf_munic['Longitude'], gdf_munic['Latitude'], crs = 4326)

# Agrupa por Divisão e une os municípios
limites_Macro = (gdf_munic.dissolve(by = 'Macrorregiao de Saude', as_index = False)[['Macrorregiao de Saude', 'geometry']])
limites_Regiao = (gdf_munic.dissolve(by = 'Regiao de Saude', as_index = False)[['Regiao de Saude','Macrorregiao de Saude', 'geometry']])
limites_DRS = (gdf_munic.dissolve(by = 'Departamento Regional de Saude', as_index = False)[['Departamento Regional de Saude', 'geometry']])
limites_GVE = (gdf_munic.dissolve(by = 'Grupo de Vigilancia Epidemiologica', as_index = False)[['Grupo de Vigilancia Epidemiologica', 'Departamento Regional de Saude', 'geometry']])

# Filtrando os dados
Antes de analisar as colunas que serão úteis para este estudo, vamos diminuir o dataframe, tirando registros (linhas) que não serão utilizadas.

In [ ]:
# df_anim = pd.read_csv("df_anim.csv")

In [13]:
# Ajustando a formatação das colunas
colunas = ['NU_ANO'], ['SG_UF_NOT'], ['ID_MUNICIP'], ['ANT_MUNIC_'], ['ANT_UF'], ['ANT_MUNIC_']

for col in colunas:
    df_anim[col] = df_anim[col].replace('', pd.NA).astype(pd.Int64Dtype())

In [14]:
df_anim = df_anim[df_anim['NU_ANO'] < 2026]  # esses dados são preliminares

In [ ]:
# teste da formatação para apenas os ocorridos em SP
# df2 = df_anim[(df_anim['SG_UF_NOT'] == 35)]

In [15]:
# Separando os casos notificados
print('QUANTIDADE DE CASOS NO ESTADO DE SÃO PAULO')
df = df_anim[(df_anim['SG_UF_NOT'] == 35) | (df_anim['ANT_UF'] == 35)]
print(f'* Ocorridos e/ou atendidos : {len(df)}')

atendidos = (df['SG_UF_NOT'] == 35) & (df['ANT_UF'] != 35)
print(f'* Atendidos mas não ocorridos : {len(df[atendidos])}')
print(f'  Código dos estados = {df[atendidos]['ANT_UF'].unique()}')

ocorridos = (df['SG_UF_NOT'] != 35) & (df['ANT_UF'] == 35)
print(f'* Ocorridos mas não atendidos : {len(df[ocorridos])}')
print(f'  Código dos estados = {df[ocorridos]['SG_UF_NOT'].unique()}')

sp = df[(df['SG_UF_NOT'] == 35) & (df['ANT_UF'] == 35)]
print(f'* Ocorridos e atendidos : {len(sp)}')

# Verificando codigos registrados
print('\nREGISTROS COM ERRO')
Codigos_Municipios = gdf_munic['Codigo Municipio'].unique()
codigo_correto = sp['ID_MUNICIP'].isin(Codigos_Municipios) & sp['ANT_MUNIC_'].isin(Codigos_Municipios)
dados = sp[codigo_correto].copy()
dados.drop(['SG_UF_NOT', 'ANT_UF'], axis = 1, inplace = True)
print(f'Registros com erro: {len(sp) - len(dados)}')
print(f'Número de casos que serão considerados: {len(dados)}')

QUANTIDADE DE CASOS NO ESTADO DE SÃO PAULO
* Ocorridos e/ou atendidos : 680550
* Atendidos mas não ocorridos : 1367
  Código dos estados = <IntegerArray>
[29, 31, 50, 15, 33, 52, 13, 41, 51, 43, 11, 42, 22, 24, 23, 32, 27, 16, 12,
 25, 26, 53, 21]
Length: 23, dtype: Int64
* Ocorridos mas não atendidos : 470
  Código dos estados = <IntegerArray>
[41, 31, 33, 32, 50, 42, 25, 43, 23, 24, 53, 27, 52, 51, 26, 29, 22, 28]
Length: 18, dtype: Int64
* Ocorridos e atendidos : 678273

REGISTROS COM ERRO
Registros com erro: 425
Número de casos que serão considerados: 677848

In [16]:
dados.shape

(677848, 73)

As variáveis ```SG_UF_NOT``` e ```ANT_UF``` foram removidas, já que o dataframe ```dados``` passa a conter apenas os acidentes ocorridos e notificados no estado de São Paulo. Além disso, a partir desta etapa, foram considerados os registros referentes ao período de 2007 a 2025. Embora a biblioteca `pysus` já disponibilize dados de 2026, estes ainda se encontram em versão preliminar e, portanto, foram desconsiderados na análise. Assim, a base final reúne mais de 662 mil casos a serem estudados.

In [ ]:
# dados.to_csv("dados.csv", index=False) #apenas para não perder os dados em caso de desconexão

## Tratamento de dados

In [ ]:
# dados = pd.read_csv("dados (3).csv")

In [ ]:
dados.columns

Index(['TP_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'ID_MUNICIP',
       'ID_REGIONA', 'DT_SIN_PRI', 'SEM_PRI', 'ANO_NASC', 'NU_IDADE_N',
       'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF', 'ID_MN_RESI',
       'ID_RG_RESI', 'ID_PAIS', 'DT_INVEST', 'ID_OCUPA_N', 'ANT_DT_ACI',
       'ANT_MUNIC_', 'ANT_TEMPO_', 'ANT_LOCA_1', 'MCLI_LOCAL', 'CLI_DOR',
       'CLI_EDEMA', 'CLI_EQUIMO', 'CLI_NECROS', 'CLI_LOCAL_', 'CLI_LOCA_1',
       'MCLI_SIST', 'CLI_NEURO', 'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT',
       'CLI_RENAL', 'CLI_OUTR_2', 'CLI_OUTR_3', 'CLI_TEMPO_', 'TP_ACIDENT',
       'ANI_TIPO_1', 'ANI_SERPEN', 'ANI_ARANHA', 'ANI_LAGART', 'TRA_CLASSI',
       'CON_SOROTE', 'NU_AMPOLAS', 'NU_AMPOL_1', 'NU_AMPOL_8', 'NU_AMPOL_6',
       'NU_AMPOL_4', 'NU_AMPO_7', 'NU_AMPO_5', 'NU_AMPOL_9', 'NU_AMPOL_3',
       'COM_LOC', 'COM_SECUND', 'COM_NECROS', 'COM_COMPOR', 'COM_DEFICT',
       'COM_APUTAC', 'COM_SISTEM', 'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC',
       'COM_CHOQUE', 'DOENCA_TRA', 'EVOLUCAO', 'DT_OBITO', 'DT_ENCERRA',
       'DT_DIGITA'],
      dtype='object')

### Colunas de localização

In [ ]:
# Regional de saúde do posto de atendimento
dados["ID_REGIONA"] = pd.to_numeric(
    dados["ID_REGIONA"].replace("", np.nan),
    errors="coerce"
)

pd.crosstab(
    index=dados["ID_REGIONA"],
    columns="Frequência",
    margins=True,
    margins_name="Total"
)

col_0       Frequência   Total
ID_REGIONA
1331             18278   18278
1332              3513    3513
1333             10992   10992
1334             11437   11437
1335             11040   11040
1336             61890   61890
1337             25149   25149
1338             10435   10435
1339             23458   23458
1340             29568   29568
1341             17301   17301
1342             77750   77750
1343             18168   18168
1344             20845   20845
1345             59550   59550
1346             13449   13449
1347              6240    6240
1348             37582   37582
1349              3240    3240
1350             33308   33308
1351             10606   10606
1352             23712   23712
1353             31848   31848
1354             66984   66984
1573             20702   20702
1574             19893   19893
1575              5651    5651
1576              4383    4383
3035               876     876
Total           677848  677848

In [ ]:
# Local de residência do paciente: queremos apenas os
dados.drop(columns=['ID_MN_RESI', 'SG_UF', 'ID_PAIS', 'ID_RG_RESI'], inplace=True);

As variáveis que indicam o local de residência do paciente não são relevantes para os objetivos deste estudo, pois a análise está focada na distância entre o local do acidente e o local de atendimento, independentemente do domicílio da vítima.

### Colunas padrões do SINAN

In [ ]:
# Verificar se todos os valores na coluna 'TP_NOT' são '2'
dados['TP_NOT'].unique()

<StringArray>
['2     ', '2']
Length: 2, dtype: string

A variável `TP_NOT` indica o tipo de notificação no SINAN, sendo o valor 2 referente a notificações individuais. Como acidentes com animais peçonhentos são eventos isolados e não transmissíveis, todos os registros assumem esse valor.

In [ ]:
# Verificar se todos os valores na coluna 'ID_AGRAVO' são 'X29'
dados['ID_AGRAVO'].unique()

<StringArray>
['X29      ', 'X29 ']
Length: 2, dtype: string

A variável `ID_AGRAVO` identifica o tipo de agravo notificado, sendo 'X29' o código utilizado para acidentes com animais peçonhentos. Como o banco de dados foi filtrado especificamente para esse tipo de ocorrência, todos os registros assumem esse valor.

In [ ]:
dados.drop(columns=['TP_NOT', 'ID_AGRAVO'], inplace=True);

### Colunas de datas
Para os objetivos desta análise, serão consideradas apenas as variáveis de data do acidente (`ANT_DT_ACI`) e de notificação (`DT_NOTIFIC`), que permitem estudar a relação temporal entre a ocorrência e o registro do evento. As demais datas, como` DT_INVEST, DT_OBITO, DT_ENCERRA e DT_DIGIT`A, referem-se a etapas administrativas ou desfechos específicos, e foram desconsideradas por não contribuírem diretamente para a análise proposta.

In [ ]:
# Conferindo se há alguma linha sem data do acidente
dados[dados['ANT_DT_ACI'].isna()]

Empty DataFrame
Columns: [DT_NOTIFIC, SEM_NOT, NU_ANO, ID_MUNICIP, ID_REGIONA, DT_SIN_PRI, SEM_PRI, ANO_NASC, NU_IDADE_N, CS_SEXO, CS_GESTANT, CS_RACA, CS_ESCOL_N, DT_INVEST, ID_OCUPA_N, ANT_DT_ACI, ANT_MUNIC_, ANT_TEMPO_, ANT_LOCA_1, MCLI_LOCAL, CLI_DOR, CLI_EDEMA, CLI_EQUIMO, CLI_NECROS, CLI_LOCAL_, CLI_LOCA_1, MCLI_SIST, CLI_NEURO, CLI_HEMORR, CLI_VAGAIS, CLI_MIOLIT, CLI_RENAL, CLI_OUTR_2, CLI_OUTR_3, CLI_TEMPO_, TP_ACIDENT, ANI_TIPO_1, ANI_SERPEN, ANI_ARANHA, ANI_LAGART, TRA_CLASSI, CON_SOROTE, NU_AMPOLAS, NU_AMPOL_1, NU_AMPOL_8, NU_AMPOL_6, NU_AMPOL_4, NU_AMPO_7, NU_AMPO_5, NU_AMPOL_9, NU_AMPOL_3, COM_LOC, COM_SECUND, COM_NECROS, COM_COMPOR, COM_DEFICT, COM_APUTAC, COM_SISTEM, COM_RENAL, COM_EDEMA, COM_SEPTIC, COM_CHOQUE, DOENCA_TRA, EVOLUCAO, DT_OBITO, DT_ENCERRA, DT_DIGITA]
Index: []

[0 rows x 67 columns]

In [ ]:
# Conferindo se há alguma linha sem data da notificação
dados[dados['DT_NOTIFIC'].isna()]

Empty DataFrame
Columns: [DT_NOTIFIC, SEM_NOT, NU_ANO, ID_MUNICIP, ID_REGIONA, DT_SIN_PRI, SEM_PRI, ANO_NASC, NU_IDADE_N, CS_SEXO, CS_GESTANT, CS_RACA, CS_ESCOL_N, DT_INVEST, ID_OCUPA_N, ANT_DT_ACI, ANT_MUNIC_, ANT_TEMPO_, ANT_LOCA_1, MCLI_LOCAL, CLI_DOR, CLI_EDEMA, CLI_EQUIMO, CLI_NECROS, CLI_LOCAL_, CLI_LOCA_1, MCLI_SIST, CLI_NEURO, CLI_HEMORR, CLI_VAGAIS, CLI_MIOLIT, CLI_RENAL, CLI_OUTR_2, CLI_OUTR_3, CLI_TEMPO_, TP_ACIDENT, ANI_TIPO_1, ANI_SERPEN, ANI_ARANHA, ANI_LAGART, TRA_CLASSI, CON_SOROTE, NU_AMPOLAS, NU_AMPOL_1, NU_AMPOL_8, NU_AMPOL_6, NU_AMPOL_4, NU_AMPO_7, NU_AMPO_5, NU_AMPOL_9, NU_AMPOL_3, COM_LOC, COM_SECUND, COM_NECROS, COM_COMPOR, COM_DEFICT, COM_APUTAC, COM_SISTEM, COM_RENAL, COM_EDEMA, COM_SEPTIC, COM_CHOQUE, DOENCA_TRA, EVOLUCAO, DT_OBITO, DT_ENCERRA, DT_DIGITA]
Index: []

[0 rows x 67 columns]

In [ ]:
dados.drop(columns=['DT_INVEST', 'DT_OBITO', 'DT_ENCERRA', 'DT_DIGITA'], inplace=True);

As colunas `SEM_PRI` e `DT_SIN_PRI`, que indicam respectivamente a semana e a data dos primeiros sintomas, foram descartadas por não serem relevantes para os objetivos da presente análise.

In [ ]:
dados.drop(columns=['SEM_PRI', 'DT_SIN_PRI'], inplace=True);

### Colunas dos sintomas e complicações clínicas
Algumas variáveis referem-se a manifestações clínicas locais e sistêmicas do acidente, ao tempo de coagulação e a complicações clínicas decorrentes do agravo. Embora essas informações tenham relevância do ponto de vista clínico e epidemiológico, elas não estão diretamente relacionadas ao objetivo central deste estudo, que consiste na análise espacial e logística da localização dos postos de soroterapia e dos fluxos de atendimento.

Além disso, parte dessas informações clínicas já é sintetizada em variáveis mais gerais, como a classificação da gravidade do acidente. Dessa forma, optou-se pela remoção dessas variáveis, a fim de manter na base apenas os atributos mais diretamente associados à caracterização espacial, temporal e assistencial dos casos.

* **Manifestações clínicas locais:** `MCLI_LOCAL`, `CLI_DOR`, `CLI_EDEMA`, `CLI_EQUIMO`, `CLI_NECROS`, `CLI_LOCAL_` e `CLI_LOCA_1`.

* **Manifestações clínicas sistêmicas:** `MCLI_SIST`, `CLI_NEURO`, `CLI_HEMORR`, `CLI_VAGAIS`, `CLI_MIOLIT`, `CLI_RENAL`, `CLI_OUTR_2`, `CLI_OUTR_3` e `CLI_TEMPO_`.

* **Complicações clínicas:** `COM_LOC`, `COM_SECUND`, `COM_NECROS`, `COM_COMPOR`, `COM_DEFICT`, `COM_APUTAC`, `COM_SISTEM`, `COM_RENAL`, `COM_EDEMA`, `COM_SEPTIC` e `COM_CHOQUE`.

In [ ]:
# Manifestacoes clinicas
dados.drop(columns=['MCLI_LOCAL', 'CLI_DOR', 'CLI_EDEMA', 'CLI_EQUIMO', 'CLI_NECROS', 'CLI_LOCAL_', 'CLI_LOCA_1'], inplace=True);

In [ ]:
# Manifestacoes sistemicas
dados.drop(columns=['MCLI_SIST', 'CLI_NEURO', 'CLI_HEMORR', 'CLI_VAGAIS', 'CLI_MIOLIT', 'CLI_RENAL', 'CLI_OUTR_2', 'CLI_OUTR_3', 'CLI_TEMPO_'], inplace=True);

In [ ]:
# Complicacoes
dados.drop(columns=['COM_LOC', 'COM_SECUND', 'COM_NECROS', 'COM_COMPOR', 'COM_DEFICT', 'COM_APUTAC', 'COM_SISTEM', 'COM_RENAL', 'COM_EDEMA', 'COM_SEPTIC', 'COM_CHOQUE'], inplace=True);

### Coluna sobre ocupação

In [ ]:
pd.crosstab(index=dados['ID_OCUPA_N'], columns='Frequência', dropna=False)

col_0       Frequência
ID_OCUPA_N
                370226
000000            2905
000000              56
010205               2
010205               1
...                ...
999994            2282
999995             125
999995              79
XXX               3348
XXX                132

[2815 rows x 1 columns]

A variável `ID_OCUPA_N`, que representa a ocupação exercida pelo paciente segundo a Classificação Brasileira de Ocupações (CBO), foi excluída da análise. Além de não estar diretamente relacionada aos objetivos do estudo, os valores presentes no campo apresentaram inconsistências e não permitiram uma categorização confiável para interpretação.

In [ ]:
dados.drop(columns=['ID_OCUPA_N'], inplace=True);

### Coluna sobre idade
Para deixar o df menor possível, apenas uma variável sobre idade será mantida.

In [ ]:
dados['ANO_NASC'].unique()

<StringArray>
['    1959', '    1942', '    1969', '    1981', '    1943', '    1952',
 '********', '    1988', '    1983', '    1962',
 ...
     '1916',     '2022',     '1908',     '1914',     '2023',     '1917',
     '2024',     '1901',     '2025',     '1900']
Length: 232, dtype: string

In [ ]:
((dados['ANO_NASC'] == '********') | (dados['ANO_NASC'].isna())).sum()

np.int64(5486)

A variável `ANO_NASC`apresenta um número considerável de registros ausente dessa informação.

In [ ]:
dados['NU_IDADE_N'].unique()

<StringArray>
['      4047', '      4065', '      4048', '      4037', '      4026',
 '      4064', '      4055', '      4036', '      4019', '      4024',
 ...
       '4107',       '4108',       '4102',       '4123',       '4115',
       '4112',       '1016',       '4124',       '1001',       '4000']
Length: 320, dtype: string

In [ ]:
(dados['NU_IDADE_N'] == 8 ).sum()

np.int64(0)

In [ ]:
(dados['NU_IDADE_N'] == 28 ).sum()

np.int64(0)

In [ ]:
(dados['NU_IDADE_N'] == 38 ).sum()

np.int64(0)

In [ ]:
(dados['NU_IDADE_N'] == 51 ).sum()

np.int64(0)

In [ ]:
idades_remover = [8, 28, 38, 51]
dados = dados[~dados['NU_IDADE_N'].isin(idades_remover)].copy()

In [ ]:
dados['NU_IDADE_N'].isin(idades_remover).sum()

np.int64(0)

A variável `NU_IDADE_N` apresenta menos inconsistência nos valores, por isso, será mantida.

In [ ]:
dados.drop(columns=['ANO_NASC'], inplace=True);
# dados.drop(columns=['NU_IDADE_N'], inplace=True);

## Dados finais

In [ ]:
dados.columns

Index(['DT_NOTIFIC', 'SEM_NOT', 'NU_ANO', 'ID_MUNICIP', 'ID_REGIONA',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N',
       'ANT_DT_ACI', 'ANT_MUNIC_', 'ANT_TEMPO_', 'ANT_LOCA_1', 'TP_ACIDENT',
       'ANI_TIPO_1', 'ANI_SERPEN', 'ANI_ARANHA', 'ANI_LAGART', 'TRA_CLASSI',
       'CON_SOROTE', 'NU_AMPOLAS', 'NU_AMPOL_1', 'NU_AMPOL_8', 'NU_AMPOL_6',
       'NU_AMPOL_4', 'NU_AMPO_7', 'NU_AMPO_5', 'NU_AMPOL_9', 'NU_AMPOL_3',
       'DOENCA_TRA', 'EVOLUCAO'],
      dtype='object')

In [ ]:
dados.shape

(677848, 32)

In [ ]:
dados

,DT_NOTIFIC,SEM_NOT,NU_ANO,ID_MUNICIP,ID_REGIONA,NU_IDADE_N,CS_SEXO,CS_GESTANT,CS_RACA,CS_ESCOL_N,...,NU_AMPOL_1,NU_AMPOL_8,NU_AMPOL_6,NU_AMPOL_4,NU_AMPO_7,NU_AMPO_5,NU_AMPOL_9,NU_AMPOL_3,DOENCA_TRA,EVOLUCAO
105,2007-07-04,200727,2007,352360,1345,4047,M,6,1,03,...,**********,**********,**********,**********,*********,*********,**********,**********,1,1
129,2007-07-18,200729,2007,350115,1353,4065,M,6,3,06,...,**********,**********,**********,**********,*********,*********,**********,**********,1,1
133,2007-07-21,200729,2007,352430,1348,4048,F,5,1,,...,**********,**********,**********,**********,*********,*********,**********,**********,2,1
147,2007-07-04,200727,2007,350820,1343,4037,F,5,1,01,...,**********,**********,**********,**********,*********,*********,**********,**********,2,
148,2007-07-17,200729,2007,351320,1343,4026,M,6,1,03,...,**********,**********,**********,**********,*********,*********,**********,**********,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4113404,2025-12-21,202552,2025,354500,1333,4032,F,5,1,08,...,,,,,,,,,2,1
4113405,2025-12-21,202552,2025,352020,1351,4021,M,6,1,09,...,,,,,,,,,2,1
4113410,2025-12-21,202552,2025,355340,1354,4079,M,6,1,06,...,,,,,,,,,2,1
4113411,2025-12-21,202552,2025,355340,1354,4044,M,6,1,09,...,,,,,,,,,2,9
4113414,2025-12-21,202552,2025,351780,1336,4048,M,6,1,,...,,,,,,,,,2,1

In [ ]:
dados.to_csv('dados_finais.csv', index=False, encoding='utf-8')